<a href="https://colab.research.google.com/github/priyeshr7/pytorch/blob/main/general_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.8.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU :{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. using CPU")

GPU is not available. using CPU


In [4]:
#using empty
a= torch.empty(2,3)

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# creates a matrix of random numberes , everytime it wil give a new matrix ,
torch.rand(2,3)

tensor([[0.4881, 0.9046, 0.2577],
        [0.6213, 0.3624, 0.7527]])

In [10]:
# this will generate the same random number matrix every time ,so it is useful when it is need to reproduce .
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor method to create the matrix
torch.tensor([[1,2,3,4],[3,4,5,6]])

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])

In [12]:
torch.arange(2,20)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
# create evenly space between 0-12
torch.linspace(0,12,10)

tensor([ 0.0000,  1.3333,  2.6667,  4.0000,  5.3333,  6.6667,  8.0000,  9.3333,
        10.6667, 12.0000])

In [14]:
torch.eye((6))

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [15]:
torch.full((2,4),4)

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [16]:
#tensor shape
r= torch.tensor([[1,2,3],[3,4,5]])
r

tensor([[1, 2, 3],
        [3, 4, 5]])

In [17]:
r.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(r)

tensor([[      904923301,               0,               0],
        [             65,       905140624, 136936299957520]])

In [19]:
torch.ones_like(r)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.zeros_like(r)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
# this doesnt work coz , rand generate numbers of float , and in 'r' we have integes
torch.rand_like(r)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [22]:
#data types
r.dtype

torch.int64

In [23]:
torch.tensor([[1,2,3],[3,4,5]],dtype=torch.int32)

tensor([[1, 2, 3],
        [3, 4, 5]], dtype=torch.int32)

In [24]:
torch.tensor([8,9,10],dtype=torch.float64)

tensor([ 8.,  9., 10.], dtype=torch.float64)

In [25]:
# using to ()
r.to(torch.float32)

tensor([[1., 2., 3.],
        [3., 4., 5.]])

# Mathematical Operations

## Scalar Operation

In [26]:
t=torch.rand(2,3)
t

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [27]:
t+3

tensor([[3.2627, 3.0428, 3.2080],
        [3.1180, 3.1217, 3.7356]])

In [28]:
t-3

tensor([[-2.7373, -2.9572, -2.7920],
        [-2.8820, -2.8783, -2.2644]])

In [29]:
t/3

tensor([[0.0876, 0.0143, 0.0693],
        [0.0393, 0.0406, 0.2452]])

In [30]:
#Mod
t%2

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [31]:
#integer division
(t*100)//3

tensor([[ 8.,  1.,  6.],
        [ 3.,  4., 24.]])

In [32]:
t**2

tensor([[0.0690, 0.0018, 0.0433],
        [0.0139, 0.0148, 0.5411]])

In [33]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [34]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [35]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [36]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [37]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [38]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [39]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

# Element Wise Operator



In [40]:
c=torch.tensor([1,-2,5,-4])
d=torch.tensor([1.2,3.4,5.6,7.8])
print(c)
print(d)

tensor([ 1, -2,  5, -4])
tensor([1.2000, 3.4000, 5.6000, 7.8000])


In [41]:
torch.abs(c)

tensor([1, 2, 5, 4])

In [42]:
torch.neg(c)

tensor([-1,  2, -5,  4])

In [43]:
torch.round(d)

tensor([1., 3., 6., 8.])

In [44]:
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [45]:
torch.floor(d)

tensor([1., 3., 5., 7.])

In [46]:
torch.clamp(d,min=-1,max=8)

tensor([1.2000, 3.4000, 5.6000, 7.8000])


# Reducing Operation

In [47]:
x =torch.randint(size=(2,4),low=0,high=10,dtype=torch.float32)
x

tensor([[0., 1., 9., 9.],
        [8., 0., 7., 0.]])

In [48]:
torch.sum(x)

tensor(34.)

In [49]:
# sum along columns
torch.sum(x,dim=0)

tensor([ 8.,  1., 16.,  9.])

In [50]:
#sum along rows
torch.sum(x,dim=1)

tensor([19., 15.])

In [51]:
# mean | to convert in mean the number should be in float | and to change it , we use change.to
torch.mean(x.to(torch.float32))

tensor(4.2500)

In [52]:
torch.mean(x,dim=0)

tensor([4.0000, 0.5000, 8.0000, 4.5000])

In [53]:
#median
torch.median(x)

tensor(1.)

In [54]:
torch.min(x)

tensor(0.)

In [55]:
torch.max(x)

tensor(9.)

In [56]:
torch.prod(x)

tensor(0.)

In [57]:
torch.std(x)

tensor(4.3342)

In [58]:
torch.var(x)

tensor(18.7857)

In [59]:
# it give the index of the min element
torch.argmin(x)

tensor(0)

In [60]:
torch.argmax(x)

tensor(2)

# Matrix Operataion

In [61]:
g=torch.randint(size=(2,3),low=0,high=10 , dtype=torch.float32)
h=torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
print(g)
print(h)


tensor([[0., 9., 5.],
        [7., 3., 9.]])
tensor([[4., 0.],
        [5., 7.],
        [5., 9.]])


In [62]:
torch.matmul(g,h)

tensor([[ 70., 108.],
        [ 88., 102.]])

In [63]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])
# dot product
torch.dot(v1,v2)

tensor(11)

In [64]:
k=torch.transpose(g,0,1)
k

tensor([[0., 7.],
        [9., 3.],
        [5., 9.]])

In [65]:
k=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(k)
torch.det(k)

tensor([[9., 7., 5.],
        [9., 8., 9.],
        [7., 9., 2.]])


tensor(-145.0000)

In [66]:
torch.inverse(k)

tensor([[ 0.4483, -0.2138, -0.1586],
        [-0.3103,  0.1172,  0.2483],
        [-0.1724,  0.2207, -0.0621]])

 # comparision Operator

In [67]:
p=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
q=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(p)
print(q)
# greater than
p>q

tensor([[6., 7., 7.],
        [8., 3., 6.],
        [1., 5., 5.]])
tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])


tensor([[ True,  True,  True],
        [False, False,  True],
        [False, False,  True]])

In [68]:
# lesser than
p<q

tensor([[False, False, False],
        [False,  True, False],
        [ True, False, False]])

In [69]:
#equals to
p==q

tensor([[False, False, False],
        [ True, False, False],
        [False,  True, False]])

In [70]:
h<=k

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

# Special functions

In [71]:
t = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
t

tensor([[6., 4., 0.],
        [8., 4., 7.]])

In [72]:
torch.log(t)

tensor([[1.7918, 1.3863,   -inf],
        [2.0794, 1.3863, 1.9459]])

In [73]:
torch.exp(t)

tensor([[4.0343e+02, 5.4598e+01, 1.0000e+00],
        [2.9810e+03, 5.4598e+01, 1.0966e+03]])

In [74]:
torch.sqrt(t)

tensor([[2.4495, 2.0000, 0.0000],
        [2.8284, 2.0000, 2.6458]])

In [75]:
torch.sigmoid(t)

tensor([[0.9975, 0.9820, 0.5000],
        [0.9997, 0.9820, 0.9991]])

In [76]:
torch.softmax(t,dim=0)


tensor([[1.1920e-01, 5.0000e-01, 9.1105e-04],
        [8.8080e-01, 5.0000e-01, 9.9909e-01]])

In [77]:
torch.relu(t)

tensor([[6., 4., 0.],
        [8., 4., 7.]])

In [78]:
# in-place operation
p.add_(q)

tensor([[ 6., 11., 10.],
        [16., 11.,  9.],
        [ 4., 10.,  5.]])

In [79]:
# here p will give the same value as p+q
p

tensor([[ 6., 11., 10.],
        [16., 11.,  9.],
        [ 4., 10.,  5.]])

In [80]:
q

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [81]:
torch.relu(p)

tensor([[ 6., 11., 10.],
        [16., 11.,  9.],
        [ 4., 10.,  5.]])

In [82]:
p.relu_()

tensor([[ 6., 11., 10.],
        [16., 11.,  9.],
        [ 4., 10.,  5.]])

# Copying a Tensor

In [83]:
r= torch.rand(2,3)
r

tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

In [84]:
b=r

In [85]:
b

tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

In [86]:
r[0][0]=0

In [87]:
r

tensor([[0.0000, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

In [88]:
b

tensor([[0.0000, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

In [89]:
# both r and b will point to the same memory location
# so if we change one , it will change the other
# to avoid this we can use clone method
id(r)

136931923669024

In [90]:
id(b)

136931923669024

In [91]:
# a new tensor with same value as r but different memory location
b=r.clone()

In [92]:
r

tensor([[0.0000, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

In [93]:
b

tensor([[0.0000, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])

# Tensor Operation on GPU

In [94]:
torch.cuda.is_available()

False

In [95]:
device = torch.device('cuda')

In [96]:
torch.rand((2,3), device=device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [97]:
a=torch.rand(2,3)
a

tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])

In [98]:
a.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [99]:
b+a

tensor([[0.0103, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

# Reshaping Tensor

In [100]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [101]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [102]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
b= torch.rand(2,3,4)
b

tensor([[[0.1659, 0.4393, 0.2243, 0.8935],
         [0.0497, 0.1780, 0.3011, 0.1893],
         [0.9186, 0.2131, 0.3957, 0.6017]],

        [[0.4234, 0.5224, 0.4175, 0.0340],
         [0.9157, 0.3079, 0.6269, 0.8277],
         [0.6594, 0.0887, 0.4890, 0.5887]]])

In [104]:
b.permute(2,0,1)

tensor([[[0.1659, 0.0497, 0.9186],
         [0.4234, 0.9157, 0.6594]],

        [[0.4393, 0.1780, 0.2131],
         [0.5224, 0.3079, 0.0887]],

        [[0.2243, 0.3011, 0.3957],
         [0.4175, 0.6269, 0.4890]],

        [[0.8935, 0.1893, 0.6017],
         [0.0340, 0.8277, 0.5887]]])

In [105]:
b.permute(2,1,0).shape
        # original=2,3,4
        # permute =4,2,3

torch.Size([4, 3, 2])

In [106]:
#unsequeeze
# normal image size -> 226,226,3
# after unsqueeze(0) '0' is the position where we want to unsqueeze  -> 1,226,226,3
c=torch.rand(226,226,3)
print(c.unsqueeze(0).shape)
print(c.unsqueeze(1).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])


In [107]:
# squeeze
d= torch.rand(1,20)

In [108]:
# it gives the shape of the tensor after removing the dimension of size 1.
d.squeeze(0).shape

torch.Size([20])

In [109]:
import numpy as np

In [110]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [111]:
b=a.numpy()
b

array([1, 2, 3])

In [112]:
type(b)

numpy.ndarray

In [113]:

c= np.array([1,2,3])
c

array([1, 2, 3])

In [114]:

torch.from_numpy(c)

tensor([1, 2, 3])