<a href="https://colab.research.google.com/github/priyeshr7/pytorch/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.0.1


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU :{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. using CPU")

GPU is not available. using CPU


In [5]:
#using empty
a= torch.empty(2,3)

In [6]:
#check type
type(a)

torch.Tensor

In [8]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# creates a matrix of random numberes , everytime it wil give a new matrix ,
torch.rand(2,3)

tensor([[0.0525, 0.7729, 0.7670],
        [0.3102, 0.9464, 0.0410]])

In [16]:
# this will generate the same random number matrix every time ,so it is useful when it is need to reproduce .
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
# using tensor method to create the matrix
torch.tensor([[1,2,3,4],[3,4,5,6]])

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])

In [23]:
torch.arange(2,20)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
# create evenly space between 0-12
torch.linspace(0,12,10)

tensor([ 0.0000,  1.3333,  2.6667,  4.0000,  5.3333,  6.6667,  8.0000,  9.3333,
        10.6667, 12.0000])

In [26]:
torch.eye((6))

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [28]:
torch.full((2,4),4)

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [31]:
#tensor shape
r= torch.tensor([[1,2,3],[3,4,5]])
r

tensor([[1, 2, 3],
        [3, 4, 5]])

In [32]:
r.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(r)

tensor([[136925877546416,  94129502867920, 136922276530384],
        [136922276537008, 136922276537632, 136922276529664]])

In [35]:
torch.ones_like(r)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [36]:
torch.zeros_like(r)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
# this doesnt work coz , rand generate numbers of float , and in 'r' we have integes
torch.rand_like(r)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [38]:
#data types
r.dtype

torch.int64

In [39]:
torch.tensor([[1,2,3],[3,4,5]],dtype=torch.int32)

tensor([[1, 2, 3],
        [3, 4, 5]], dtype=torch.int32)

In [40]:
torch.tensor([8,9,10],dtype=torch.float64)

tensor([ 8.,  9., 10.], dtype=torch.float64)

In [41]:
# using to ()
r.to(torch.float32)

tensor([[1., 2., 3.],
        [3., 4., 5.]])

# Mathematical Operations

## Scalar Operation

In [5]:
t=torch.rand(2,3)
t

tensor([[0.3791, 0.8481, 0.9046],
        [0.5991, 0.1038, 0.8375]])

In [45]:
t+3

tensor([[3.4826, 3.9588, 3.1291],
        [3.5870, 3.3136, 3.7080]])

In [46]:
t-3

tensor([[-2.5174, -2.0412, -2.8709],
        [-2.4130, -2.6864, -2.2920]])

In [47]:
t/3

tensor([[0.1609, 0.3196, 0.0430],
        [0.1957, 0.1045, 0.2360]])

In [48]:
#Mod
t%2

tensor([[0.4826, 0.9588, 0.1291],
        [0.5870, 0.3136, 0.7080]])

In [49]:
#integer division
(t*100)//3

tensor([[16., 31.,  4.],
        [19., 10., 23.]])

In [6]:
t**2

tensor([[0.1437, 0.7192, 0.8183],
        [0.3589, 0.0108, 0.7015]])

In [9]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.4613, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])
tensor([[0.1291, 0.6078, 0.9538],
        [0.2572, 0.4545, 0.5164]])


In [10]:
a+b

tensor([[0.5905, 1.6006, 1.9536],
        [1.2282, 1.0415, 0.9798]])

In [11]:
a-b

tensor([[ 0.3322,  0.3849,  0.0461],
        [ 0.7138,  0.1325, -0.0529]])

In [12]:
a*b

tensor([[0.0596, 0.6034, 0.9537],
        [0.2497, 0.2668, 0.2393]])

In [13]:
a/b

tensor([[3.5728, 1.6333, 1.0483],
        [3.7757, 1.2916, 0.8976]])

In [14]:
a**b

tensor([[0.9049, 0.9956, 0.9999],
        [0.9925, 0.7850, 0.6723]])

In [15]:
a%b

tensor([[0.0740, 0.3849, 0.0461],
        [0.1995, 0.1325, 0.4635]])

# Element Wise Operator



In [16]:
c=torch.tensor([1,-2,5,-4])
d=torch.tensor([1.2,3.4,5.6,7.8])
print(c)
print(d)

tensor([ 1, -2,  5, -4])
tensor([1.2000, 3.4000, 5.6000, 7.8000])


In [17]:
torch.abs(c)

tensor([1, 2, 5, 4])

In [18]:
torch.neg(c)

tensor([-1,  2, -5,  4])

In [19]:
torch.round(d)

tensor([1., 3., 6., 8.])

In [20]:
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [21]:
torch.floor(d)

tensor([1., 3., 5., 7.])

In [22]:
torch.clamp(d,min=-1,max=8)

tensor([1.2000, 3.4000, 5.6000, 7.8000])


# Reducing Operation

In [23]:
x =torch.randint(size=(2,4),low=0,high=10,dtype=torch.float32)
x

tensor([[8., 7., 0., 6.],
        [8., 1., 8., 8.]])

In [24]:
torch.sum(x)

tensor(46.)

In [25]:
# sum along columns
torch.sum(x,dim=0)

tensor([16.,  8.,  8., 14.])

In [26]:
#sum along rows
torch.sum(x,dim=1)

tensor([21., 25.])

In [27]:
# mean | to convert in mean the number should be in float | and to change it , we use change.to
torch.mean(x.to(torch.float32))

tensor(5.7500)

In [39]:
torch.mean(x,dim=0)

tensor([5.0000, 6.0000, 5.0000, 5.5000])

In [40]:
#median
torch.median(x)

tensor(5.)

In [45]:
torch.min(x)

tensor(3.)

In [46]:
torch.max(x)

tensor(7.)

In [49]:
torch.prod(x)

tensor(432180.)

In [50]:
torch.std(x)

tensor(1.8468)

In [51]:
torch.var(x)

tensor(3.4107)

In [52]:
# it give the index of the min element
torch.argmin(x)

tensor(0)

In [53]:
torch.argmax(x)

tensor(4)

# Matrix Operataion

In [50]:
g=torch.randint(size=(2,3),low=0,high=10 , dtype=torch.float32)
h=torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
print(g)
print(h)


tensor([[9., 7., 3.],
        [3., 6., 8.]])
tensor([[1., 7.],
        [1., 8.],
        [6., 5.]])


In [51]:
torch.matmul(g,h)

tensor([[ 34., 134.],
        [ 57., 109.]])

In [ ]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])
# dot product 
torch.dot(v1,v2)

tensor(11)

In [52]:
k=torch.transpose(g,0,1)
k

tensor([[9., 3.],
        [7., 6.],
        [3., 8.]])

In [57]:
k=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(k)
torch.det(k)

tensor([[1., 3., 2.],
        [6., 0., 0.],
        [0., 6., 3.]])


tensor(18.0000)

In [58]:
torch.inverse(k)

tensor([[ 0.0000,  0.1667,  0.0000],
        [-1.0000,  0.1667,  0.6667],
        [ 2.0000, -0.3333, -1.0000]])

 # comparision Operator 

In [86]:
p=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
q=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(p)
print(q)
# greater than 
p>q

tensor([[3., 8., 4.],
        [1., 3., 7.],
        [5., 7., 4.]])
tensor([[7., 4., 1.],
        [4., 1., 5.],
        [1., 5., 4.]])


tensor([[False,  True,  True],
        [False,  True,  True],
        [ True,  True, False]])

In [63]:
# lesser than 
p<q

tensor([[ True, False, False],
        [False,  True,  True],
        [ True, False,  True]])

In [66]:
#equals to 
p==q

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [40]:
h<=k

tensor([[True, True],
        [True, True],
        [True, True]])

# Special functions

In [78]:
t = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
t

tensor([[2., 3., 7.],
        [9., 2., 9.]])

In [70]:
torch.log(t)

tensor([[1.7918, 1.6094, 1.0986],
        [1.7918, 1.7918, 0.0000]])

In [71]:
torch.exp(t)

tensor([[403.4288, 148.4132,  20.0855],
        [403.4288, 403.4288,   2.7183]])

In [72]:
torch.sqrt(t)

tensor([[2.4495, 2.2361, 1.7321],
        [2.4495, 2.4495, 1.0000]])

In [73]:
torch.sigmoid(t)

tensor([[0.9975, 0.9933, 0.9526],
        [0.9975, 0.9975, 0.7311]])

In [79]:
torch.softmax(t,dim=0)


tensor([[9.1105e-04, 7.3106e-01, 1.1920e-01],
        [9.9909e-01, 2.6894e-01, 8.8080e-01]])

In [80]:
torch.relu(t)

tensor([[2., 3., 7.],
        [9., 2., 9.]])

In [81]:
p.add_(q)

tensor([[14.,  0.,  2.],
        [12.,  8., 14.],
        [12.,  0., 14.]])

In [83]:
p

tensor([[14.,  0.,  2.],
        [12.,  8., 14.],
        [12.,  0., 14.]])

In [84]:
q

tensor([[14.,  0.,  2.],
        [12.,  8., 14.],
        [12.,  0., 14.]])

In [87]:
torch.relu(p)

tensor([[3., 8., 4.],
        [1., 3., 7.],
        [5., 7., 4.]])

In [88]:
p.relu_()

tensor([[3., 8., 4.],
        [1., 3., 7.],
        [5., 7., 4.]])

# Copying a Tensor 

In [89]:
r= torch.rand(2,3)
r

tensor([[0.5510, 0.2134, 0.9333],
        [0.4908, 0.9402, 0.4733]])

In [95]:
r=b

In [96]:
b

tensor([[0.4613, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])

In [97]:
r[0][0]=0

In [98]:
r

tensor([[0.0000, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])

In [99]:
b

tensor([[0.0000, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])

In [100]:
id(r)

5417386144

In [101]:
id(b)

5417386144

In [102]:
b=r.clone()

In [103]:
r

tensor([[0.0000, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])

In [104]:
b

tensor([[0.0000, 0.9928, 0.9999],
        [0.9710, 0.5870, 0.4635]])

# Tensor Operation on GPU

In [105]:
torch.cuda.is_available()

False

In [106]:
device = torch.device('cuda')

In [108]:
torch.rand((2,3), device=device)

AssertionError: Torch not compiled with CUDA enabled

In [109]:
a=torch.rand(2,3)
a

tensor([[0.8844, 0.6136, 0.3932],
        [0.8161, 0.9615, 0.6150]])

In [110]:
a.to(device)

AssertionError: Torch not compiled with CUDA enabled

In [111]:
b+a

tensor([[0.8844, 1.6064, 1.3931],
        [1.7871, 1.5485, 1.0785]])

# Reshaping Tensor 

In [119]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [120]:
# reshape 
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [122]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [123]:
b= torch.rand(2,3,4)
b

tensor([[[0.8697, 0.2886, 0.1609, 0.5470],
         [0.2916, 0.3007, 0.9047, 0.5065],
         [0.4475, 0.7316, 0.8078, 0.2540]],

        [[0.4690, 0.2155, 0.9186, 0.4133],
         [0.3272, 0.4185, 0.7512, 0.3196],
         [0.0624, 0.5358, 0.1351, 0.4622]]])

In [124]:
b.permute(2,0,1)

tensor([[[0.8697, 0.2916, 0.4475],
         [0.4690, 0.3272, 0.0624]],

        [[0.2886, 0.3007, 0.7316],
         [0.2155, 0.4185, 0.5358]],

        [[0.1609, 0.9047, 0.8078],
         [0.9186, 0.7512, 0.1351]],

        [[0.5470, 0.5065, 0.2540],
         [0.4133, 0.3196, 0.4622]]])

In [125]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [131]:
#unsequeeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [132]:
# squeeze
d= torch.rand(1,20)

In [134]:
d.squeeze(0).shape

torch.Size([20])

In [147]:
import numpy as np

In [144]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [138]:
b=a.numpy()
b

array([1, 2, 3])

In [139]:
type(b)

numpy.ndarray

In [148]:
c= np.array([1,2,3])
c

array([1, 2, 3])

In [149]:
torch.from_numpy(c)

tensor([1, 2, 3])